# Whether to use sympy parsing (basic simplification)
use_sympy: false

# Whether to replace log and sqrt by log(abs) and sqrt(abs)
use_abs: false

# Maximal integer in symbolic expressions
max_int: 20

# Number of digits in the mantissa
float_precision: 2

use_skeleton: false

swapping: false

refine: false
refine_steps: 10

all_type: false
# Number of tokens for the mantissa (must be a divisor of float_precision+1)
mantissa_len: 1

# Maximal order of magnitude
max_exponent: 10

# Maximal order of magnitude in prefactors
max_exponent_prefactor: 1

n_words: -1

noisy_text_input: false

